
DROP SCHEMA IF EXISTS public CASCADE
; 
CREATE SCHEMA public AUTHORIZATION postgres
;
-- Defina o schema padrão 
SET search_path TO public
;
--ALTER DATABASE SGAS SET timezone TO 'America/Sao_Paulo'
;
SET TimeZone TO 'America/Sao_Paulo'
;

CREATE TABLE usuario
(
    id               bigint generated by default as identity ,
    is_administrador boolean NOT NULL,
    email            character varying(255) ,
    nome             character varying(255) ,
    senha            character varying(255) ,
    
    PRIMARY KEY (id),
    UNIQUE (email)
)
;

--ALTER TABLE IF EXISTS usuario OWNER to postgres;

create table servico (
    id        bigint not null generated by default as identity, 
    vagas     integer not null, 
    data      date, 
    descricao varchar(255), 
    tipo      varchar(255), 
    titulo    varchar(255), 
    turno     varchar(255), 
    
    primary key (id)
);

CREATE TABLE candidatura_servico
(
    usuario_id       bigint NOT NULL,
    servico_id       bigint NOT NULL,
    
    data_candidatura date,
    status           varchar(255) ,

    PRIMARY KEY (servico_id, usuario_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario (id) ,
    FOREIGN KEY (servico_id) REFERENCES servico (id) 
)
;

CREATE TABLE animal
(
    id              bigint NOT NULL generated by default as identity,
    porte           varchar(1),
    sexo            varchar(1),
    data_nascimento date,
    descricao       varchar(500) ,
    imagem_url      varchar(255) ,
    nome            varchar(255) not null,
    raca            varchar(255) ,
    
    PRIMARY KEY (id)
)
;

CREATE TABLE doacao_financeira
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    valor       double precision NOT NULL,
    usuario_id  bigint,
    observacao  varchar(255) ,
    
    PRIMARY KEY (id),
    FOREIGN KEY (usuario_id) REFERENCES usuario (id) 
)
;

CREATE TABLE solicitacao_adocao
(
    id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    animal_id           bigint,
    usuario_id          bigint,

    data_solicitacao    date,
    status              varchar(255) ,
    
    PRIMARY KEY (id),
    FOREIGN KEY (usuario_id) REFERENCES usuario (id) ,
    FOREIGN KEY (animal_id) REFERENCES animal (id)
)
;

CREATE TABLE usario_fav_animal
(
    animal_id   bigint NOT NULL,
    usuario_id  bigint NOT NULL,
    
    FOREIGN KEY (animal_id) REFERENCES animal (id) ,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id) 
)
;